upd

diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -58,6 +58,23 @@ c)
         echo "done"
         exit 0
     fi
+    echo "Running bin/${FILE_NAME}..."
+    echo ""
+    ./bin/${FILE_NAME} $ARGS
+    ;;
+cpp)
+    echo "Compiling ${FILE_NAME}.cpp..."
+    # Ensure 'bin' directory exists for compiled binaries
+    mkdir -p "bin"
+    clang++ -Wall -Wextra -lm $C_FLAGS "$FILE_PATH" -o "bin/${FILE_NAME}"
+    if [[ $? -ne 0 ]]; then
+        echo "Compilation failed."
+        exit 1
+    fi
+    if $BUILD_ONLY; then
+        echo "done"
+        exit 0
+    fi
     echo ""
     echo "Running bin/${FILE_NAME}..."
     echo ""
@@ -222,11 +239,6 @@ sh)
     echo "Running ${FILE_NAME}.sh script...."
     echo ""
     bash $FILE_PATH
-    ;;
-html)
-    echo "starting http server..."
-    echo ""
-    http-server --port 5173
     ;;
 *)
     echo "Unsupported file type: .$EXT"
